player-parkours:
  enabled: true
  world: "player_parkours"
  world-void: true
  platform:
    y: 64
    size: 5
    block: "STONE"
  plot-size: 64
  plot-gap: 256
  give-creative: true
  allow-worldedit: true
  worldedit:
    max-blocks-per-operation: 3000
    deny:
      - set
      - replace
      - stack
      - paste
      - fill
      - line
      - cyl
      - sphere
      - smooth
      - walls
      - faces
      - hcyl
      - hsphere
    allow: []
  max-per-player: 3
  create-cooldown-seconds: 0
  top-hologram-size: 5
  storage: "sqlite"  # options: sqlite, yaml
  outline:
    enabled: true
    border-block: "YELLOW_CONCRETE"
    corner-block: "SEA_LANTERN"
  world-rules:
    block-natural-spawns: true
  borders:
    use-worldborder: true
  rewards:
    enabled: false
    interval-days: 7
    winners: 3
    command: "give %player% diamond 3"
  items:
    restart:
      slot: 0
      material: "SLIME_BALL"
      name: "&aRestart Parkour"
      lore:
        - "&7Return to start and reset timer"
    checkpoint:
      slot: 1
      material: "ENDER_PEARL"
      name: "&bLast Checkpoint"
      lore:
        - "&7Teleport back to your latest checkpoint"
    leave:
      slot: 8
      material: "RED_BED"
      name: "&cLeave Parkour"
      lore:
        - "&7Exit parkour mode"
    hide:
      slot: 2
      visible:
        material: "ENDER_EYE"
        name: "&fHide Players"
        lore:
          - "&7Click to hide other players."
      hidden:
        material: "ENDER_EYE"
        name: "&fShow Players"
        lore:
          - "&7Click to show other players."
collisions:
  disable: true
debug: false
config-version: 2
